<?php


/**
 * Implementation of hook_menu().
 */
function pagination_menu() {
 
  $menu['admin/settings/pagination'] = array(
    'title' => 'Input Data',
    'description' => 'Input data for pagination.', 
	  array('!block' => l(t('block administration'), 'admin/build/block')),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pagination_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'menu_name' => 'pagination',
  );
  
  return $menu;
}

/**
* Define the input data form.
*/
function pagination_admin_settings() {
 $form['queries'] = array('#type' => 'fieldset', '#title' => t('Inputing data'));
  
  $form['queries']['execution1'] = array('#type' => 'textfield',
    '#title' => t('Student Name'),
    '#default_value' => variable_get('execution1', ''),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('Type your name.'),
  );
  
  $form['queries']['execution2'] = array('#type' => 'textfield',
    '#title' => t('Student Roll'),
    '#default_value' => variable_get('execution2', 0),
    '#size' => 4,
    '#maxlength' => 4,
    '#description' => t('Input your roll.'),
  );
  
  $form['queries']['execution3'] = array('#type' => 'textfield',
    '#title' => t('Student Address'),
    '#default_value' => variable_get('execution3', ''),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('Input your address.'),
  );
  
  $form['queries']['submit1'] = array('#type' => 'submit', 
  '#value'=> t('Insert Data') );
  
  //return system_settings_form($form);
  return $form;
}


/**
 * Handle submission of the pagination form and saving
 * of the data to the database.
 */
function pagination_admin_settings_submit($form, $form_state) {
  global $nid;
  
  $name = $form_state['values']['execution1'];
  $roll = $form_state['values']['execution2'];
  $address = $form_state['values']['execution3'];
  
  
  db_query("INSERT INTO {student} (name, roll, address) VALUES ('%s',%d,'%s')", "$name", $roll, "$address");
  
  drupal_set_message(t('Data has been successfully inserted.'));
}


