<?php

/* space == separator */

$emoticons=array();

$emoticons[]=':wink: wink.png';
$emoticons[]=':smile: smile.png';
$emoticons[]=':angry: angry.png';
$emoticons[]=':bored: bored.png';
$emoticons[]=':sad: sad.png';
$emoticons[]=':cursing: cursing.png';
$emoticons[]=':confused: confused.png';
$emoticons[]=':kiss: kiss.png';
$emoticons[]=':laugh: laugh.png';
$emoticons[]=':tongue: tongue1.png';
$emoticons[]=':bigtongue: tongue2.png';
$emoticons[]=':happy: happy1.png';
$emoticons[]=':happpy: happy2.png';
$emoticons[]=':unhappy: unhappy.png';
$emoticons[]=':sleep: sleep.png';
$emoticons[]=':unsure: unsure.png';
$emoticons[]=':blink: blink.png';
$emoticons[]=':blush: blush1.png';
$emoticons[]=':grin: grin1.png';
$emoticons[]=':biggrin: grin2.png';
$emoticons[]=':mad: mad.png';
$emoticons[]=':ohmy: ohmy.png';
$emoticons[]=':devil: devil.png';
$emoticons[]=':cool: cool.png';
$emoticons[]=':huh: huh.png';
$emoticons[]=':glare: glare.png';
$emoticons[]=':blushin: blush2.png';
$emoticons[]=':mellow: mellow.png';
$emoticons[]=':vomit: vomit.png';
$emoticons[]=':wub: wub.png';

$aliases=array();
$aliases[]=':) smile.png';
$aliases[]=':( sad.png';
$aliases[]=';-) wink.png';
$aliases[]=':-) smile.png';
$aliases[]=':-( sad.png';
$aliases[]='lol laugh.png';
$aliases[]='rofl laugh.png';

?>